# CodeCraftAI Workflow Manifest
# This file is the single source of truth for the project's workflow,
# directory structure, and automation rules.

# Section 1: Internationalization (I18n)
languages:
  default: en
  supported:
    - en
    - zh

# Section 2: Directory Structure
# Maps conceptual areas to their physical locations in the repository.
directories:
  tasks: tasks/
  # All documentation is now centralized in the docs/ directory.
  specs: docs/specs/
  adr: docs/adr/
  project_docs: project_docs/
  project_logs: project_logs/
  # Core templates remain within the system's .codecraft directory.
  templates: .codecraft/templates/

# Section 3: Task Management Workflow
tasks:
  status_map:
    backlog: tasks/backlog/
    todo: tasks/todo/
    in_progress: tasks/in_progress/
    done: tasks/done/
    archive: tasks/archive/
  templates:
    # Task templates are user-facing and stay in the tasks/ directory.
    en: tasks/template.en.md
    zh: tasks/template.zh.md

# Section 4: Specification Management
specs:
  templates:
    # Spec templates are part of the system docs and are now in docs/specs/.
    en: docs/specs/template.en.md
    zh: docs/specs/template.zh.md

# Section 5: ADR Management
adr:
  templates:
    en: docs/adr/template.en.md
    zh: docs/adr/template.zh.md

# Section 6: Git Workflow Configuration
git:
  branch_prefixes:
    feat: "feat"
    fix: "fix"
    docs: "docs"
    style: "style"
    refactor: "refactor"
    test: "test"
    chore: "chore"
